baseURL = "/"
languageCode = "en-us"
title = "Genesys Experience as a Service"
theme = "modernize"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "false"
uglyurls = "true"
relativeURLs = true
enableEmoji = true

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]